# Generated by Django 6.0.4 on 2026-05-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TierPolicy',
            new_name='RolePolicy',
        ),
        migrations.AlterModelOptions(
            name='rolepolicy',
            options={'verbose_name': 'Role Policy', 'verbose_name_plural': 'Role Policies'},
        ),
        migrations.RenameField(
            model_name='rolepolicy',
            old_name='tier',
            new_name='role',
        ),
    ]
